theme: jekyll-theme-time-machine

title: [Data Sci PSY]
description: [Introduction to data science for graduate students in Psychology]

show_downloads: true


theme: jekyll-theme-cayman

# Navigation links
navbar-links:
  Home: /index.md
  Lessons: /toc.md
  Resources: /resources.md
  Contact: /contact_info.md

